Fix user.player
When doing `user.player`, I'm getting the error `NoMethodError: undefined method `present?' for #<Hash:0x00007fe2eff07650>`. Since no other method seems to be using this check before parsing the response, I'm suggesting its removal. Also, if Spotify returns an empty response, return a player object so that one can still call the play methods.